package {{PACKAGE_NAME}}.core.model

import org.junit.Assert.assertEquals
import org.junit.Test

class GreetingTest {
    @Test
    fun greetingHoldsData() {
        val greeting = Greeting(
            title = "{{DISPLAY_NAME}}",
            subtitle = "Generated by BiucingCLI",
        )

        assertEquals("{{DISPLAY_NAME}}", greeting.title)
    }
}
