services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        GOPROXY: ${GOPROXY:-https://proxy.golang.org,direct}
        GOSUMDB: ${GOSUMDB:-sum.golang.org}
    working_dir: /workspace
    command: air -c .air.toml
    environment:
      CONFIG_FILE: /workspace/configs/config.yaml
      GOCACHE: /workspace/.cache/go-build
      GOMODCACHE: /workspace/.cache/go-mod
      GOLANGCI_LINT_CACHE: /workspace/.cache/golangci-lint
    ports:
      - "${HOST_PORT:-{{HTTP_PORT}}}:{{HTTP_PORT}}"
    stop_grace_period: 15s
    volumes:
      - .:/workspace
      - web-service-go-build:/workspace/.cache/go-build
      - web-service-go-mod:/workspace/.cache/go-mod
      - web-service-golangci-lint:/workspace/.cache/golangci-lint

volumes:
  web-service-go-build:
  web-service-go-mod:
  web-service-golangci-lint:
