server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    error_page 404 /404.html;
    location = /404.html { internal; }
    location = /__spa-fallback.html { return 404; }
    location /assets/ { try_files $uri =404; }
    location ~ \.data$ { try_files $uri =404; }
    location / {
        try_files $uri $uri/index.html =404;
    }
}
