package {{PACKAGE_NAME}}.feature.home

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import {{PACKAGE_NAME}}.core.model.Greeting

@Composable
@Suppress("ktlint:standard:function-naming")
fun HomeRoute() {
    val greeting = Greeting(
        title = "{{DISPLAY_NAME}}",
        subtitle = "Generated by BiucingCLI",
    )

    Text(
        text = "${greeting.title}\n${greeting.subtitle}",
        style = MaterialTheme.typography.headlineMedium,
    )
}
