package {{PACKAGE_NAME}}.feature.home

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import {{PACKAGE_NAME}}.core.designsystem.AppSectionCard
import {{PACKAGE_NAME}}.core.designsystem.BiucingSpacing
import {{PACKAGE_NAME}}.core.designsystem.StatusBadge
import {{PACKAGE_NAME}}.core.model.Greeting

@Composable
@Suppress("ktlint:standard:function-naming")
fun HomeRoute() {
    val greeting = Greeting(
        title = "{{DISPLAY_NAME}}",
        subtitle = "Generated by BiucingCLI",
    )

    AppSectionCard(
        title = greeting.title,
        eyebrow = "Starter Overview",
    ) {
        Column(verticalArrangement = Arrangement.spacedBy(BiucingSpacing.small)) {
            StatusBadge(text = "Compose baseline ready")
            Text(
                text = greeting.subtitle,
                style = MaterialTheme.typography.bodyLarge,
            )
            Text(
                text = "Use the generated design system tokens and starter components as the baseline for new features.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}
