#!/usr/bin/env bash
set -euo pipefail

./scripts/setup-xcode
brew bundle
mise install
if [ ! -f Dependencies/components.lock.json ]; then
  make components-bootstrap
fi
make generate
./scripts/doctor
