-- Local fixture only. Provision production roles independently.
CREATE ROLE "{{SERVICE_NAME}}_app" LOGIN PASSWORD 'local-app-only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE "{{SERVICE_NAME}}_migrator" LOGIN PASSWORD 'local-migrate-only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
SELECT format('REVOKE ALL ON DATABASE %I FROM PUBLIC', current_database()) \gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO "{{SERVICE_NAME}}_app", "{{SERVICE_NAME}}_migrator"', current_database()) \gexec
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO "{{SERVICE_NAME}}_app";
GRANT USAGE, CREATE ON SCHEMA public TO "{{SERVICE_NAME}}_migrator";
ALTER DEFAULT PRIVILEGES FOR ROLE "{{SERVICE_NAME}}_migrator" IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{{SERVICE_NAME}}_app";
ALTER DEFAULT PRIVILEGES FOR ROLE "{{SERVICE_NAME}}_migrator" IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO "{{SERVICE_NAME}}_app";
