package {{PACKAGE_NAME}}.feature.home

import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import {{PACKAGE_NAME}}.core.designsystem.AppSectionCard
import {{PACKAGE_NAME}}.core.model.AnalysisService
import {{PACKAGE_NAME}}.core.model.HomeOutput
import kotlinx.coroutines.launch

@Composable
@Suppress("ktlint:standard:function-naming")
fun HomeRoute(
    model: HomeModel,
    title: String = "{{DISPLAY_NAME_KOTLIN}}",
    onOutput: (HomeOutput) -> Unit,
) {
    val state by model.state.collectAsState()
    val scope = rememberCoroutineScope()
    AppSectionCard(title = title, eyebrow = "Starter Overview") {
        Column {
            Text("Generated by BiucingCLI")
            Text(state.result?.toString() ?: "—")
            if (state.failed) Text(stringResource(R.string.home_failed))
            Button(onClick = { scope.launch { model.run() } }, enabled = !state.running) {
                Text(stringResource(if (state.running) R.string.home_loading else R.string.home_calculate))
            }
            Button(onClick = { onOutput(HomeOutput.ShowSettings) }) { Text(stringResource(R.string.home_settings)) }
        }
    }
}

@Preview
@Composable
@Suppress("ktlint:standard:function-naming")
private fun HomePreview() {
    val model =
        remember {
            HomeFactory(
                object : AnalysisService {
                    override suspend fun analyze(values: LongArray): Long = 42
                },
            ).makeModel()
        }
    HomeRoute(model, onOutput = {})
}
