export class AppConfig {
  static readonly displayName: string = '{{DISPLAY_NAME}}';
  static readonly bundleName: string = '{{BUNDLE_NAME}}';
  static readonly moduleName: string = '{{HARMONY_MODULE_NAME}}';
  static readonly abilityName: string = '{{ABILITY_NAME}}';
  static readonly versionName: string = '{{HARMONY_VERSION_NAME}}';
  static readonly versionCode: string = '{{HARMONY_VERSION_CODE}}';
  static readonly releaseChannel: string = 'local';
}
