name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UV_PROJECT_ENVIRONMENT: .venv
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: uv sync --group dev
      - name: Lint
        run: uv run ruff check src tests
      - name: Type check
        run: uv run mypy src
      - name: Test
        run: uv run pytest --cov=biucingcli --cov-report=term-missing
