name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install hatch
        run: pip install hatch
      - name: Install project
        run: hatch env create
      - name: Lint
        run: hatch run lint
      - name: Type check
        run: hatch run typer-check
      - name: Test
        run: hatch run test
